name: Publish Mod

on:
  push:
    tags:
      - '[A-Za-z0-9]+-[0-9]+\.[0-9]+\.[0-9]+'
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Install SteamCMD
        id: steamcmd
        uses: Lordfirespeed/setup-steamcmd@v2

      - name: Restore SteamCMD authentication
        shell: pwsh
        env:
          CONFIG_VDF_CONTENTS: ${{ secrets.CONFIG_VDF_CONTENTS }}
        run: |
          $configDir = Join-Path "${{ steps.steamcmd.outputs.directory }}" "config"

          New-Item -ItemType Directory -Path $configDir | Out-Null

          $CONFIG_VDF_CONTENTS | 
            Out-File `
              -FilePath (Join-Path $configDir "config.vdf") `
              -Encoding utf8 `
              -NoNewline

      - name: Test SteamCMD
        shell: pwsh
        env:
          STEAM_USER: ${{ secrets.STEAM_USER }}
        run: |
          & steamcmd +login "$env:STEAM_USER" +quit
          if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 1) {
            exit $LASTEXITCODE
          }


      - name: Install Shapez 2
        shell: pwsh
        env:
          STEAM_USER: ${{ secrets.STEAM_USER }}
        run: |
          # specify the install directory and store it in an environment variable
          $installDir = "$env:GITHUB_WORKSPACE\shapez2"
          
          # create the folder
          New-Item -ItemType Directory -Path $installDir | Out-Null

          # install!
          & steamcmd `
            +force_install_dir $installDir `
            +login "$env:STEAM_USER" `
            +app_update 2162800 validate `
            +quit

      - name: Determine mod
        shell: bash
        run: |
          TAG="$GITHUB_REF_NAME"
          echo "Running for tag: $TAG"

          MOD_NAME="${TAG%-*}"
          VERSION="${TAG##*-}"

          # find the mod files
          MOD_DIR="$GITHUB_WORKSPACE/$MOD_NAME"
          PROJECT=$(find "$MOD_DIR" -maxdepth 1 -name '*.csproj' -print -quit)

          if [[ ! -d "$MOD_DIR" ]]; then
            echo "ERROR: Could not find mod directory in $MOD_DIR"
            exit 1
          fi

          if [[ -z "$PROJECT" ]]; then
            echo "ERROR: No .csproj file found in $MOD_DIR"
            exit 1
          fi

          # store the values into the environment for use later
          echo "MOD_NAME=$MOD_NAME" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "MOD_DIR=$MOD_DIR" >> "$GITHUB_ENV"
          echo "PROJECT=$PROJECT" >> "$GITHUB_ENV"

      - name: Build mod
        shell: bash
        run: |
          dotnet build "$PROJECT" \
            --configuration Release \
            -p:OutputPath="$GITHUB_WORKSPACE/build/$MOD_NAME"

            echo "Build output:"
            find "$GITHUB_WORKSPACE/build/$MOD_NAME" -type f -print

          # Verify version numbers